# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '音频视频' do

use_frameworks!


pod 'MBProgressHUD', '~> 1.1.0'
pod 'SnapKit'
pod 'R.swift'
pod 'TZImagePickerController'

pod 'AliyunOSSiOS'

#pod 'SDWebImage', '~> 4.3.3'
pod 'SDWebImage', '~> 4.1.2'

pod 'UICircularProgressRing', '~> 2.1.0'

end
