# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '音频视频' do

use_frameworks!

pod 'SnapKit'
pod 'R.swift'
pod 'TZImagePickerController', '~> 2.1.3'

end
